CLOUD-12367 - Added logging to ./common/*; fixed other logging issues
# Overview
- We didn't have logging in the `./common/*` modules
- We had issues with logging -- `AttributeError: 'NoneType' object has no attribute 'isEnabledFor'`
- Removed logging to file
- Changed logging config to simplify
  - Removed additional formatters
  - Checking if `env` is `local`. if it is, going to sends to `console` with simple formatter. if not `local`, sends to `console` in `json`.

# `Local` Env Example
```log
2024-02-02T22:16:20.037170Z [info     ] HTTP Request: POST https://cloud-test.hdw.mx/cdb/oauth2/introspect "HTTP/1.1 200 OK" [httpx] filename=_client.py func_name=_send_single_request lineno=1013
2024-02-02T22:16:20.068691Z [info     ] HTTP Request: POST https://cloud-test.hdw.mx/cdb/oauth2/introspect "HTTP/1.1 200 OK" [httpx] filename=_client.py func_name=_send_single_request lineno=1013
2024-02-02T22:16:20.099577Z [info     ] HTTP Request: POST https://cloud-test.hdw.mx/cdb/oauth2/introspect "HTTP/1.1 200 OK" [httpx] filename=_client.py func_name=_send_single_request lineno=1013
2024-02-02T22:16:20.129483Z [info     ] HTTP Request: POST https://cloud-test.hdw.mx/cdb/oauth2/introspect "HTTP/1.1 401 Unauthorized" [httpx] filename=_client.py func_name=_send_single_request lineno=1013
2024-02-02T22:16:20.153164Z [info     ] HTTP Request: POST https://fba7f02e-e158-4ce3-822f-b93d6c9e17d9.relay.relay.cloud.hdw.mx/rest/v3/system/cloud/sync "HTTP/1.1 200 OK" [httpx] filename=_client.py func_name=_send_single_request lineno=1013
```

# Anything else (`prod`, `ci`) Example
```log
{"request": "GET /", "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", "event": "request_started", "request_id": "2c2fdc2d-89fc-421f-b854-9b04e70a3eb1", "ip": "127.0.0.1", "timestamp": "2024-02-02T22:18:06.170901Z", "logger": "django_structlog.middlewares.request", "level": "info"}
{"code": 404, "request": "GET /", "event": "request_finished", "request_id": "2c2fdc2d-89fc-421f-b854-9b04e70a3eb1", "ip": "127.0.0.1", "user_id": null, "timestamp": "2024-02-02T22:18:06.193018Z", "logger": "django_structlog.middlewares.request", "level": "info"}
{"event": "Not Found: /", "timestamp": "2024-02-02T22:18:06.193170Z", "logger": "django.request", "level": "warning", "func_name": "log_response", "lineno": 241, "filename": "log.py"}
```

- Updated tests for logger to not check for logs going to the file

Related to CLOUD-12367

(cherry picked from commit aa893ac991629e17522cb7da5b4017019f224d9b)