CLOUD-14958: Fix Keyword Argument Error in WebSocket Logging
#### Overview

This merge request addresses a critical issue in the desktop notifications service where logging WebSocket connections caused a `TypeError` due to unexpected keyword arguments. Additionally, it enhances the logging configuration and WebSocket logging details for more comprehensive insights.

#### Fix

1. **Logging Configuration Enhancements**
    - Introduced a `configure_structlog` function to set up Structlog.
    - Updated `setup_logging` function to include `configure_structlog`.
    - Enhanced global variable `_logger` initialization to use Structlog instead of Quart's logger.

2. **WebSocket Connection Logging Enhancements**
    - Improved logging statements in WebSocket connection management to include detailed `client_address`, `path`, and `headers`.

#### Resolution

1. **Modified Files**

    - `desktop_notifications/logging_config.py`
        - Corrected imports and adjusted code formatting.
        - Introduced `configure_structlog` function.
        - Enhanced `setup_logging` to configure Structlog and update `_logger`.
        - All loggers should propragate upwards to root. Additionally, they don't have any handlers or formatters
          - Root has queue handler to handle processing off main thread.

    - `desktop_notifications/notification_provider/main.py`
        - Updated WebSocket connection logging to provide more detailed client information.
        - Improved logs for client connection and disconnection events.

#### Test ran

Upon running notification's provider app and then running the following script

```python

import asyncio
import websockets
import aiohttp


async def notify_webhook(data):
    async with aiohttp.ClientSession() as session:
        webhook_url = "http://localhost:8000/0.0.0.0:8000/notification_provider/api/v1/subscribe"
        async with session.post(webhook_url, json=data) as response:
            return await response.text()


async def listen_to_websocket(uri):
    async with websockets.connect(uri) as websocket:
        while True:
            message = await websocket.recv()
            print(f"Received message: {message}")
            data = {"message": message}
            response = await notify_webhook(data)
            print(f"Webhook response: {response}")


async def main():
    uri = "ws://0.0.0.0:8000/notification_provider/api/v1/subscribe"
    await listen_to_websocket(uri)


if __name__ == "__main__":
    asyncio.run(main())
```

it generated the following logs

```
{"event": "Application startup complete", "timestamp": "2024-10-24T01:18:52.101794Z", "logger": "quart.app", "level": "info"}
{"event": "Running on http://0.0.0.0:8000 (CTRL + C to quit)", "timestamp": "2024-10-24T01:18:52.102931Z", "logger": "hypercorn.error", "level": "info", "lineno": 92, "func_name": "info", "filename": "logging.py"}
[2024-10-23 18:18:52 -0700] [82335] [INFO] Running on http://0.0.0.0:8000 (CTRL + C to quit)
{"event": "request_finished", "x_forwarded_for": null, "request_id": "1f86318b-c341-4c35-b9f3-e4e94cfd1855", "x_amzn_trace_id": null, "timestamp": "2024-10-24T01:19:18.018530Z", "logger": "hypercorn.access", "level": "info", "host": "127.0.0.1:52228", "status": 200, "method": "GET", "path": "/notification_provider/api/v1/ping", "query_params": "", "response_size": "4", "request_duration_ms": 0.8, "lineno": 74, "func_name": "access", "filename": "logging.py"}
{"client_address": "127.0.0.1", "path": "/notification_provider/api/v1/subscribe", "headers": {"Remote-Addr": "127.0.0.1", "Host": "0.0.0.0:8000", "Upgrade": "websocket", "Connection": "Upgrade", "Sec-Websocket-Key": "dZiToKh0JBB4pki4mQE3qw==", "Sec-Websocket-Version": "13", "Sec-Websocket-Extensions": "permessage-deflate; client_max_window_bits", "User-Agent": "Python/3.12 websockets/13.1"}, "event": "Client connected", "timestamp": "2024-10-24T01:19:23.316299Z", "logger": "quart.app", "level": "info"}
{"client_address": "127.0.0.1", "path": "/notification_provider/api/v1/subscribe", "event": "Client disconnected", "timestamp": "2024-10-24T01:19:23.316512Z", "logger": "quart.app", "level": "info"}
{"event": "request_finished", "timestamp": "2024-10-24T01:19:23.316867Z", "logger": "hypercorn.access", "level": "info", "host": "127.0.0.1:52231", "status": 200, "method": "GET", "path": "/notification_provider/api/v1/subscribe", "query_params": "", "response_size": "0", "request_duration_ms": 0.75, "lineno": 74, "func_name": "access", "filename": "logging.py"}
```

Important ones

```json
{
  "client_address": "127.0.0.1",
  "path": "/notification_provider/api/v1/subscribe",
  "headers": {
    "Remote-Addr": "127.0.0.1",
    "Host": "0.0.0.0:8000",
    "Upgrade": "websocket",
    "Connection": "Upgrade",
    "Sec-Websocket-Key": "dZiToKh0JBB4pki4mQE3qw==",
    "Sec-Websocket-Version": "13",
    "Sec-Websocket-Extensions": "permessage-deflate; client_max_window_bits",
    "User-Agent": "Python/3.12 websockets/13.1"
  },
  "event": "Client connected",
  "timestamp": "2024-10-24T01:19:23.316299Z",
  "logger": "quart.app",
  "level": "info"
}
```

```json
{
  "client_address": "127.0.0.1",
  "path": "/notification_provider/api/v1/subscribe",
  "event": "Client disconnected",
  "timestamp": "2024-10-24T01:19:23.316512Z",
  "logger": "quart.app",
  "level": "info"
}
```
```json
{
  "event": "request_finished",
  "timestamp": "2024-10-24T01:19:23.316867Z",
  "logger": "hypercorn.access",
  "level": "info",
  "host": "127.0.0.1:52231",
  "status": 200,
  "method": "GET",
  "path": "/notification_provider/api/v1/subscribe",
  "query_params": "",
  "response_size": "0",
  "request_duration_ms": 0.75,
  "lineno": 74,
  "func_name": "access",
  "filename": "logging.py"
}
```

# Loggers in application
```
# All Loggers and their info (basically sending everything to root logger)
root
  Handlers: QueueHandler
  Formatters: %(message)s
  Propagate: True
pkg_resources
  extern
    packaging
      tags
        Handlers: 
        Formatters: 
        Propagate: True
concurrent
  futures
    Handlers: 
    Formatters: 
    Propagate: True
asyncio
  Handlers: 
  Formatters: 
  Propagate: True
hpack
  table
    Handlers: 
    Formatters: 
    Propagate: True
  hpack
    Handlers: 
    Formatters: 
    Propagate: True
aiohttp
  access
    Handlers: 
    Formatters: 
    Propagate: True
  client
    Handlers: 
    Formatters: 
    Propagate: True
  internal
    Handlers: 
    Formatters: 
    Propagate: True
  server
    Handlers: 
    Formatters: 
    Propagate: True
  web
    Handlers: 
    Formatters: 
    Propagate: True
  websocket
    Handlers: 
    Formatters: 
    Propagate: True
charset_normalizer
  Handlers: 
  Formatters: 
  Propagate: True
quart
  app
    Handlers: 
    Formatters: 
    Propagate: True
hypercorn
  access
    Handlers: 
    Formatters: 
    Propagate: True
  error
    Handlers: 
    Formatters: 
    Propagate: True
```